### ISSUE TITLE
WARN: Function 'wait' is unknown

### ISSUE THREAD

**Issue by ghoullier** [WarpJS/beta#17]
## api.js
```js
function wait(delay = 1000) {
  return new Promise((resolve) => setTimeout(resolve, delay));
}

async function hello() {
  'warp +server -client';

  await wait();

  return `Hello from Node`;
}

export { hello };
```

## index.js
```js
// import WarpJS
import { defaultWarper as warper } from '@warpjs/warp';
import engine from '@warpjs/engine';

import { hello } from './api';

// init WarpJS
engine.init({ config: { logging: 'info' } });

engine.setErrorHandler((error) => {
  console.error('WarpJSError', error);
});

document.addEventListener('DOMContentLoaded', async () => {
  const message = await warper.call(hello);
  console.log(message);
});
```

This code raise the following error in my browser

```console
engine-prod.js:6 WARN: Function 'wait' is unknown
```

**Comment by jpl-scale** [comment]
Yes, the message is not good enough. We try to say something better and display something actionnable.

@NicolasPennec could you explain the issue here to unblock him?

**Comment by NicolasPennec** [comment]
@ghoullier your `wait` function is unknown by Warp because, it is in the "client" scope, but call from the "server" scope. By default, only functions with a [directive](https://warpjs.dev/docs/api/directives) will be parsed by Warp.

Some ways to fix it:

- add a directive to set scope:

```js
function wait(delay = 1000) {
  'warp +server -client';
  return new Promise((resolve) => setTimeout(resolve, delay));
}
```

-  move function in the 'server' scope of the `hello` function:

```js
async function hello() {
  'warp +server -client';

  function wait(delay = 1000) {
    return new Promise((resolve) => setTimeout(resolve, delay));
  }

  await wait();

  return `Hello from Node`;
}
```

For this last example, if you need to share the `wait` function, simply create a module and import it `const wait = require "./wait"` in the `hello` function.

**Comment by NicolasPennec** [comment]
@ghoullier These solutions are right for you?

**Comment by ghoullier** [comment]
Yes, thanks for your reply!
